# Copyright 2026 Björn (frenetik.B)
# SPDX-License-Identifier: Apache-2.0

"""Public API for the experimental deterministic RPF process validator."""

from rpf_validator.classification import (
    CLASSIFICATION_PROPOSAL_SCHEMA_VERSION,
    MAX_EVIDENCE_EXCERPT_LENGTH,
    PROVIDER_CONFIDENCE_SCALE_ID,
    ClassificationProposal,
    ContentDigest,
    DigestAlgorithm,
    DigestCanonicalization,
    EvidenceFragment,
    FrameCandidate,
    ProposalInputReference,
    ProposalRole,
    ProposalUncertainty,
    ProviderKind,
    ProviderMetadata,
    verify_source_payload,
)
from rpf_validator.classification_parsing import (
    load_classification_proposal,
    parse_classification_proposal,
    parse_classification_proposal_json,
)
from rpf_validator.enums import (
    PROCESS_STATUS_PRIORITY,
    CompetenceStatus,
    ProcessStatus,
    ReasonCode,
    ReferenceFrameClass,
    ReferenceFrameStatus,
    RevisionScope,
    RuleId,
    RuleStatus,
)
from rpf_validator.errors import InputValidationError
from rpf_validator.models import (
    INPUT_SCHEMA_VERSION,
    RESULT_SCHEMA_VERSION,
    Calibration,
    CandidateAction,
    CompetenceAssessment,
    Conflict,
    DeclaredConstraint,
    EvidenceSource,
    ExpectedEffect,
    Hypothesis,
    Observation,
    ReferenceFrame,
    RuleResult,
    TerminationState,
    TimeHorizon,
    UncertaintyItem,
    UncertaintyReport,
    ValidatorConfig,
    ValidatorInput,
    ValidatorResult,
)
from rpf_validator.evaluator import evaluate
from rpf_validator.parsing import load_input, parse_input, parse_json
from rpf_validator.schema import (
    CLASSIFICATION_PROPOSAL_SCHEMA_RESOURCE,
    INPUT_SCHEMA_RESOURCE,
    load_classification_proposal_schema,
    load_input_schema,
)
from rpf_validator.serialization import to_json, to_primitive
from rpf_validator.state_machine import (
    ALLOWED_TRANSITIONS,
    STATE_MACHINE_MAX_TRANSITIONS,
    STATE_MACHINE_TRACE_VERSION,
    InconsistentResultStatusError,
    InvalidTransitionError,
    RPFState,
    StateMachineError,
    StateMachineErrorCode,
    StateMachineStepLimitError,
    StateMachineTrace,
    TransitionEvent,
    TransitionRecord,
    UnsupportedResultContractError,
    run_state_machine,
    transition,
)

__version__ = "0.5.0.dev0"

__all__ = [
    "INPUT_SCHEMA_VERSION",
    "INPUT_SCHEMA_RESOURCE",
    "CLASSIFICATION_PROPOSAL_SCHEMA_RESOURCE",
    "CLASSIFICATION_PROPOSAL_SCHEMA_VERSION",
    "ALLOWED_TRANSITIONS",
    "MAX_EVIDENCE_EXCERPT_LENGTH",
    "PROCESS_STATUS_PRIORITY",
    "PROVIDER_CONFIDENCE_SCALE_ID",
    "RESULT_SCHEMA_VERSION",
    "STATE_MACHINE_MAX_TRANSITIONS",
    "STATE_MACHINE_TRACE_VERSION",
    "__version__",
    "Calibration",
    "CandidateAction",
    "ClassificationProposal",
    "CompetenceAssessment",
    "CompetenceStatus",
    "Conflict",
    "ContentDigest",
    "DeclaredConstraint",
    "DigestAlgorithm",
    "DigestCanonicalization",
    "EvidenceSource",
    "EvidenceFragment",
    "ExpectedEffect",
    "Hypothesis",
    "InconsistentResultStatusError",
    "InputValidationError",
    "InvalidTransitionError",
    "Observation",
    "ProcessStatus",
    "ProposalInputReference",
    "ProposalRole",
    "ProposalUncertainty",
    "ProviderKind",
    "ProviderMetadata",
    "RPFState",
    "ReasonCode",
    "ReferenceFrame",
    "ReferenceFrameClass",
    "ReferenceFrameStatus",
    "FrameCandidate",
    "RevisionScope",
    "RuleId",
    "RuleResult",
    "RuleStatus",
    "StateMachineError",
    "StateMachineErrorCode",
    "StateMachineStepLimitError",
    "StateMachineTrace",
    "TerminationState",
    "TimeHorizon",
    "TransitionEvent",
    "TransitionRecord",
    "UncertaintyItem",
    "UncertaintyReport",
    "ValidatorConfig",
    "ValidatorInput",
    "ValidatorResult",
    "UnsupportedResultContractError",
    "evaluate",
    "load_classification_proposal",
    "load_classification_proposal_schema",
    "load_input",
    "load_input_schema",
    "parse_input",
    "parse_json",
    "parse_classification_proposal",
    "parse_classification_proposal_json",
    "run_state_machine",
    "to_json",
    "to_primitive",
    "transition",
    "verify_source_payload",
]
