# Copyright 2026 Björn (frenetik.B)
# SPDX-License-Identifier: Apache-2.0

"""Public API for the experimental RPF validator data model."""

from rpf_validator.enums import (
    PROCESS_STATUS_PRIORITY,
    CompetenceStatus,
    ProcessStatus,
    ReasonCode,
    ReferenceFrameClass,
    ReferenceFrameStatus,
    RevisionScope,
    RuleId,
    RuleStatus,
)
from rpf_validator.errors import InputValidationError
from rpf_validator.models import (
    INPUT_SCHEMA_VERSION,
    RESULT_SCHEMA_VERSION,
    Calibration,
    CandidateAction,
    CompetenceAssessment,
    Conflict,
    DeclaredConstraint,
    EvidenceSource,
    ExpectedEffect,
    Hypothesis,
    Observation,
    ReferenceFrame,
    RuleResult,
    TerminationState,
    TimeHorizon,
    UncertaintyItem,
    UncertaintyReport,
    ValidatorConfig,
    ValidatorInput,
    ValidatorResult,
)
from rpf_validator.serialization import to_json, to_primitive

__all__ = [
    "INPUT_SCHEMA_VERSION",
    "PROCESS_STATUS_PRIORITY",
    "RESULT_SCHEMA_VERSION",
    "Calibration",
    "CandidateAction",
    "CompetenceAssessment",
    "CompetenceStatus",
    "Conflict",
    "DeclaredConstraint",
    "EvidenceSource",
    "ExpectedEffect",
    "Hypothesis",
    "InputValidationError",
    "Observation",
    "ProcessStatus",
    "ReasonCode",
    "ReferenceFrame",
    "ReferenceFrameClass",
    "ReferenceFrameStatus",
    "RevisionScope",
    "RuleId",
    "RuleResult",
    "RuleStatus",
    "TerminationState",
    "TimeHorizon",
    "UncertaintyItem",
    "UncertaintyReport",
    "ValidatorConfig",
    "ValidatorInput",
    "ValidatorResult",
    "to_json",
    "to_primitive",
]
